[package]
name = "iced_reorderable"
version = "0.1.0"
authors = ["Joonas Satka <joonas.satka@gmail.com>"]
edition = "2021"

[dependencies.iced]
git = "https://github.com/iced-rs/iced/"
rev = "4bbb5cbc1f8b2a0ee8e09be18071368df3ba5bbd"
features = ["advanced"]

[workspace]
members = ["examples/*"]
