[package]
name = "todos"
version = "0.1.0"
authors = ["Joonas Satka <joonas.satka@gmail.com>"]
edition = "2021"
publish = false

[dependencies.iced]
git = "https://github.com/iced-rs/iced/"
rev = "4bbb5cbc1f8b2a0ee8e09be18071368df3ba5bbd"

[dependencies]
iced_reorderable = { path = "../.." }
